server:
  host: "0.0.0.0"
  port: 7777

registry:
  heartbeat_interval: "10s"
  service_ttl: "30s"

mongodb:
  uri: "mongodb://admin:password123@localhost:27017"
  database: "soundwave"
  collections:
    users: "users"
    menus: "menus"
    tokens: "tokens"

jwt:
  secret: "your-secret-key"
  expire_hours: 24 